version: "3.8"

services:
  http:
    volumes:
      - ./wordpress:/var/www/apps/wpapp
    build:
      context: "./docker"
      dockerfile: "web.Dockerfile"
    networks:
      - network
    ports:
      - 443:443
    depends_on:
      - db
  db:
    build:
      context: "./docker"
      dockerfile: "db.Dockerfile"
    restart: always
    networks:
      - network
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 10challenge
      MYSQL_DATABASE: "10up_challenge_development"
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    command: "--default-authentication-plugin=mysql_native_password"
networks:
  network:
